"""Create reproducible diagnostics for the organizer TTC baseline.

This script consumes the six practice prediction CSVs generated by the
unmodified baseline. It does not train or modify the predictor.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import cv2
import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.patches import Rectangle  # noqa: E402


TRIPS = [f"T0{i}-Sample" for i in range(1, 7)]
DISPLAY_TTC_CAP = 10.0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--practice-root", type=Path, default=Path("Practice_Dataset"))
    parser.add_argument(
        "--predictions-dir",
        type=Path,
        default=Path("ai_cv/outputs/predictions/baseline_official"),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("ai_cv/outputs/reports/baseline_official/visualizations"),
    )
    parser.add_argument(
        "--starter-root",
        type=Path,
        default=Path("Package_starterkit/package_starterkit"),
    )
    return parser.parse_args()


def load_predictions(predictions_dir: Path) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    for trip_id in TRIPS:
        path = predictions_dir / f"{trip_id}.csv"
        frame = pd.read_csv(path)
        required = {"frame_id", "timestamp", "predicted_ttc", "ground_truth_ttc"}
        missing = required.difference(frame.columns)
        if missing:
            raise ValueError(f"{path} missing columns: {sorted(missing)}")
        if len(frame) != 600:
            raise ValueError(f"{path} has {len(frame)} rows; expected 600")
        frame["trip_id"] = trip_id
        frames.append(frame)

    data = pd.concat(frames, ignore_index=True)
    data["predicted_ttc"] = pd.to_numeric(data["predicted_ttc"], errors="raise")
    data["ground_truth_ttc"] = pd.to_numeric(data["ground_truth_ttc"], errors="raise")
    data["gt_danger"] = data["ground_truth_ttc"] < 2.0
    data["pred_danger"] = data["predicted_ttc"] < 2.0
    data["outcome"] = np.select(
        [
            data["gt_danger"] & data["pred_danger"],
            ~data["gt_danger"] & data["pred_danger"],
            data["gt_danger"] & ~data["pred_danger"],
        ],
        ["TP", "FP", "FN"],
        default="TN",
    )
    return data


def display_ttc(values: pd.Series) -> np.ndarray:
    array = values.to_numpy(dtype=float)
    return np.where(np.isfinite(array), np.minimum(array, DISPLAY_TTC_CAP), DISPLAY_TTC_CAP)


def plot_timelines(data: pd.DataFrame, output_dir: Path) -> None:
    fig, axes = plt.subplots(3, 2, figsize=(17, 12), sharex=True, sharey=True)
    for axis, trip_id in zip(axes.flat, TRIPS, strict=True):
        trip = data[data["trip_id"] == trip_id]
        seconds = trip["timestamp"].to_numpy()
        gt = display_ttc(trip["ground_truth_ttc"])
        pred = display_ttc(trip["predicted_ttc"])
        axis.axhspan(0, 2, color="#ffdddd", alpha=0.85, label="Danger <2s")
        axis.axhspan(2, 3, color="#fff1cc", alpha=0.75, label="Critical <3s")
        axis.plot(seconds, gt, color="#111111", linewidth=2.0, label="Ground truth")
        axis.plot(seconds, pred, color="#d62728", linewidth=1.0, alpha=0.85, label="Baseline")
        axis.set_title(trip_id)
        axis.set_ylim(0, 10.3)
        axis.set_xlim(0, 30)
        axis.grid(alpha=0.2)
        axis.text(
            0.99,
            0.96,
            f"FN={(trip.outcome == 'FN').sum()}  FP={(trip.outcome == 'FP').sum()}",
            transform=axis.transAxes,
            ha="right",
            va="top",
            fontsize=9,
            bbox={"facecolor": "white", "alpha": 0.8, "edgecolor": "none"},
        )
    axes[0, 0].legend(loc="upper left", ncols=2, fontsize=8)
    fig.supxlabel("Trip time (seconds)")
    fig.supylabel("TTC displayed at max 10 s (inf is plotted at 10 s)")
    fig.suptitle("Organizer stereo baseline: predicted TTC vs ground truth", fontsize=16)
    fig.tight_layout()
    fig.savefig(output_dir / "ttc_timelines.png", dpi=160, bbox_inches="tight")
    plt.close(fig)


def plot_failure_counts(data: pd.DataFrame, output_dir: Path) -> None:
    counts = (
        data[data["outcome"].isin(["TP", "FP", "FN"])]
        .groupby(["trip_id", "outcome"])
        .size()
        .unstack(fill_value=0)
        .reindex(TRIPS)
    )
    for column in ["TP", "FP", "FN"]:
        if column not in counts:
            counts[column] = 0
    counts = counts[["TP", "FP", "FN"]]

    fig, axis = plt.subplots(figsize=(13, 6.5))
    x = np.arange(len(TRIPS))
    width = 0.25
    colors = {"TP": "#2ca02c", "FP": "#ff7f0e", "FN": "#d62728"}
    for offset, column in enumerate(counts.columns):
        bars = axis.bar(x + (offset - 1) * width, counts[column], width, label=column, color=colors[column])
        axis.bar_label(bars, padding=2, fontsize=9)
    axis.set_xticks(x, TRIPS)
    axis.set_ylabel("Frame count at the 2-second danger threshold")
    axis.set_title("Baseline error counts: false alarms dominate T03; misses dominate T04/T05/T06")
    axis.legend()
    axis.grid(axis="y", alpha=0.2)
    fig.tight_layout()
    fig.savefig(output_dir / "danger_confusion_counts.png", dpi=170, bbox_inches="tight")
    counts.to_csv(output_dir / "danger_confusion_counts.csv")
    plt.close(fig)


def plot_scatter(data: pd.DataFrame, output_dir: Path) -> None:
    finite_gt = data[np.isfinite(data["ground_truth_ttc"])].copy()
    finite_gt["display_pred"] = np.where(
        np.isfinite(finite_gt["predicted_ttc"]),
        np.minimum(finite_gt["predicted_ttc"], DISPLAY_TTC_CAP),
        DISPLAY_TTC_CAP,
    )
    finite_gt["display_gt"] = np.minimum(finite_gt["ground_truth_ttc"], DISPLAY_TTC_CAP)

    fig, axis = plt.subplots(figsize=(9, 8))
    for trip_id in TRIPS:
        trip = finite_gt[finite_gt["trip_id"] == trip_id]
        axis.scatter(trip["display_gt"], trip["display_pred"], s=18, alpha=0.55, label=trip_id)
    axis.plot([0, 10], [0, 10], "k--", linewidth=1.5, label="Ideal")
    axis.axvline(2, color="#d62728", linestyle=":", linewidth=1)
    axis.axhline(2, color="#d62728", linestyle=":", linewidth=1)
    axis.set_xlim(0, 10.2)
    axis.set_ylim(0, 10.2)
    axis.set_xlabel("Ground-truth TTC (capped at 10 s)")
    axis.set_ylabel("Predicted TTC (capped at 10 s; inf=10 s)")
    axis.set_title("Poor calibration: predictions do not follow the ideal diagonal")
    axis.grid(alpha=0.2)
    axis.legend(fontsize=8, ncols=2)
    fig.tight_layout()
    fig.savefig(output_dir / "ttc_scatter.png", dpi=170, bbox_inches="tight")
    plt.close(fig)


def pick_one(data: pd.DataFrame, trip_id: str, outcome: str) -> pd.Series:
    candidates = data[(data["trip_id"] == trip_id) & (data["outcome"] == outcome)].copy()
    if candidates.empty:
        raise ValueError(f"No {outcome} candidate in {trip_id}")
    if outcome == "FN":
        candidates["rank"] = np.where(np.isfinite(candidates["predicted_ttc"]), 0, 1)
        return candidates.sort_values(["rank", "ground_truth_ttc"], ascending=[False, True]).iloc[0]
    if outcome == "FP":
        candidates["rank"] = np.where(np.isfinite(candidates["ground_truth_ttc"]), 0, 1)
        return candidates.sort_values(["rank", "predicted_ttc"], ascending=[False, True]).iloc[0]
    candidates["abs_error"] = np.abs(candidates["predicted_ttc"] - candidates["ground_truth_ttc"])
    return candidates.sort_values("abs_error").iloc[0]


def select_cases(data: pd.DataFrame) -> pd.DataFrame:
    requests = [
        ("T01-Sample", "FN"),
        ("T05-Sample", "FN"),
        ("T06-Sample", "FN"),
        ("T03-Sample", "FP"),
        ("T05-Sample", "FP"),
        ("T04-Sample", "TP"),
    ]
    return pd.DataFrame([pick_one(data, trip, outcome) for trip, outcome in requests]).reset_index(drop=True)


def fmt_ttc(value: float) -> str:
    return "inf" if not math.isfinite(float(value)) else f"{float(value):.2f}s"


def draw_roi(axis: plt.Axes, width: int, height: int) -> None:
    x0, x1 = int(width * 0.35), int(width * 0.65)
    y0, y1 = int(height * 0.50), int(height * 0.85)
    axis.add_patch(Rectangle((x0, y0), x1 - x0, y1 - y0, fill=False, edgecolor="#00ffff", linewidth=2.5))


def plot_failure_montage(cases: pd.DataFrame, practice_root: Path, output_dir: Path) -> None:
    fig, axes = plt.subplots(3, 2, figsize=(16, 11))
    colors = {"FN": "#d62728", "FP": "#ff7f0e", "TP": "#2ca02c"}
    for axis, (_, case) in zip(axes.flat, cases.iterrows(), strict=True):
        trip_id = str(case["trip_id"])
        frame_id = int(case["frame_id"])
        path = practice_root / trip_id / "kitti" / "image_2" / f"{frame_id:06d}.jpg"
        image = cv2.cvtColor(cv2.imread(str(path)), cv2.COLOR_BGR2RGB)
        axis.imshow(image)
        draw_roi(axis, image.shape[1], image.shape[0])
        outcome = str(case["outcome"])
        axis.set_title(
            f"{outcome} | {trip_id} frame {frame_id} ({float(case['timestamp']):.2f}s)\n"
            f"GT={fmt_ttc(case['ground_truth_ttc'])}, baseline={fmt_ttc(case['predicted_ttc'])}",
            color=colors[outcome],
            fontweight="bold",
        )
        axis.axis("off")
    fig.suptitle("Representative outcomes; cyan rectangle is the baseline's only ROI", fontsize=16)
    fig.tight_layout()
    fig.savefig(output_dir / "failure_frame_montage.png", dpi=170, bbox_inches="tight")
    plt.close(fig)


def plot_stereo_diagnostics(
    cases: pd.DataFrame,
    practice_root: Path,
    starter_root: Path,
    output_dir: Path,
) -> None:
    sys.path.insert(0, str(starter_root.resolve()))
    from team_kit.baseline_ttc_predictor import BaselineTTCPredictor

    selected = pd.concat(
        [cases[cases["outcome"] == outcome].head(1) for outcome in ["FN", "FP", "TP"]],
        ignore_index=True,
    )
    fig, axes = plt.subplots(len(selected), 3, figsize=(16, 4.2 * len(selected)))
    for row_index, (_, case) in enumerate(selected.iterrows()):
        trip_id = str(case["trip_id"])
        frame_id = int(case["frame_id"])
        trip_root = practice_root / trip_id / "kitti"
        calibration = json.loads((trip_root / "calibration_info.txt").read_text(encoding="utf-8"))
        predictor = BaselineTTCPredictor(calibration)
        left_bgr = cv2.imread(str(trip_root / "image_2" / f"{frame_id:06d}.jpg"))
        right_bgr = cv2.imread(str(trip_root / "image_3" / f"{frame_id:06d}.jpg"))
        disparity = predictor._compute_disparity(left_bgr, right_bgr)
        depth = predictor._disparity_to_depth(disparity)
        h, w = disparity.shape
        x0, x1 = int(w * 0.35), int(w * 0.65)
        y0, y1 = int(h * 0.50), int(h * 0.85)
        roi_depth = depth[y0:y1, x0:x1]
        valid_depth = roi_depth[np.isfinite(roi_depth)]
        median_depth = float(np.median(valid_depth)) if valid_depth.size else math.inf
        valid_ratio = valid_depth.size / roi_depth.size

        axes[row_index, 0].imshow(cv2.cvtColor(left_bgr, cv2.COLOR_BGR2RGB))
        draw_roi(axes[row_index, 0], w, h)
        axes[row_index, 0].set_title(
            f"{case['outcome']} {trip_id} #{frame_id}\n"
            f"GT={fmt_ttc(case['ground_truth_ttc'])}, pred={fmt_ttc(case['predicted_ttc'])}"
        )
        axes[row_index, 0].axis("off")

        disparity_view = np.where(disparity > 0.5, disparity, np.nan)
        axes[row_index, 1].imshow(disparity_view, cmap="magma", vmin=0.5, vmax=64)
        draw_roi(axes[row_index, 1], w, h)
        axes[row_index, 1].set_title("SGBM disparity; black/blank = invalid")
        axes[row_index, 1].axis("off")

        depth_view = np.where(np.isfinite(roi_depth), roi_depth, np.nan)
        image = axes[row_index, 2].imshow(depth_view, cmap="viridis_r", vmin=1.5, vmax=40)
        axes[row_index, 2].set_title(
            f"ROI depth only\nmedian={fmt_ttc(median_depth).replace('s', 'm')}, valid={valid_ratio:.1%}"
        )
        axes[row_index, 2].axis("off")
        fig.colorbar(image, ax=axes[row_index, 2], fraction=0.046, pad=0.04, label="meters")

    fig.suptitle("Why fixed-ROI stereo is unstable: sparse disparity and mixed surfaces", fontsize=16)
    fig.tight_layout()
    fig.savefig(output_dir / "stereo_roi_diagnostics.png", dpi=170, bbox_inches="tight")
    plt.close(fig)


def compute_temporal_diagnostics(
    cases: pd.DataFrame,
    practice_root: Path,
    starter_root: Path,
    output_dir: Path,
) -> None:
    """Replay only as far as selected frames and expose the five-depth regression state."""
    sys.path.insert(0, str(starter_root.resolve()))
    from team_kit.baseline_ttc_predictor import BaselineTTCPredictor
    from team_kit.dataset_loader import TripDataset

    requested = {(str(row.trip_id), int(row.frame_id)) for row in cases.itertuples()}
    records: list[dict[str, object]] = []
    for trip_id in sorted({trip for trip, _ in requested}):
        trip_cases = sorted(frame_id for trip, frame_id in requested if trip == trip_id)
        last_needed = trip_cases[-1]
        dataset = TripDataset(practice_root / trip_id)
        predictor = BaselineTTCPredictor(dataset.load_calibration())
        for frame in dataset.iter_frames():
            if frame.frame_id > last_needed:
                break
            left = dataset.load_left(frame.frame_id)
            right = dataset.load_right(frame.frame_id)
            prediction = predictor.predict(frame.frame_id, frame.timestamp, left, right)
            if frame.frame_id not in trip_cases:
                continue
            history = list(predictor._depth_history)
            closing_speed = predictor._estimate_closing_speed() if len(history) >= 2 else 0.0
            current_depth = history[-1][1] if history and math.isclose(history[-1][0], frame.timestamp) else math.nan
            records.append(
                {
                    "trip_id": trip_id,
                    "frame_id": frame.frame_id,
                    "timestamp": frame.timestamp,
                    "roi_depth_history_m": ";".join(f"{depth:.4f}" for _, depth in history),
                    "current_roi_median_depth_m": round(current_depth, 4),
                    "estimated_closing_speed_mps": round(closing_speed, 4),
                    "recomputed_ttc_s": round(prediction, 4) if math.isfinite(prediction) else "inf",
                }
            )
    pd.DataFrame(records).to_csv(output_dir / "selected_temporal_diagnostics.csv", index=False)


def main() -> int:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    data = load_predictions(args.predictions_dir)
    cases = select_cases(data)
    plot_timelines(data, args.output_dir)
    plot_failure_counts(data, args.output_dir)
    plot_scatter(data, args.output_dir)
    plot_failure_montage(cases, args.practice_root, args.output_dir)
    plot_stereo_diagnostics(cases, args.practice_root, args.starter_root, args.output_dir)
    compute_temporal_diagnostics(cases, args.practice_root, args.starter_root, args.output_dir)
    cases.to_csv(args.output_dir / "selected_failure_cases.csv", index=False)
    print(f"Wrote baseline visualizations to {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
